package query

var (
	// list of valid classification values to be used for search
	classes = []string{
		"Animal.amphibian",
		"Animal.bird",
		"Animal.dog",
		"Animal.fish",
		"Animal.insect",
		"Animal.mammal",
		"Animal.racehorse",
		"Animal.reptile",
		"Event.activity",
		"Event.airplane_crash",
		"Event.award",
		"Event.coup",
		"Event.crime",
		"Event.festival",
		"Event.financial",
		"Event.genocide",
		"Event.legal",
		"Event.legislation",
		"Event.massacre",
		"Event.military_operation",
		"Event.motor_race",
		"Event.pandemic",
		"Event.political",
		"Event.religion",
		"Event.social",
		"Event.space_mission",
		"Event.sport",
		"Event.sporting_event",
		"Event.sports_action",
		"Event.terrorist_attack",
		"Event.time_management",
		"Event.trade_show",
		"Event.trial",
		"Event.us_constitution",
		"Event.war",
		"Event.weather",
		"Health.alternative_medicine",
		"Health.antibody",
		"Health.antigen",
		"Health.artery",
		"Health.body_part",
		"Health.bone",
		"Health.cancer",
		"Health.cell",
		"Health.condition",
		"Health.diet",
		"Health.disorder",
		"Health.enzyme",
		"Health.gene",
		"Health.hormone",
		"Health.muscle",
		"Health.organ",
		"Health.peptide",
		"Health.pharmaceutical",
		"Health.rate",
		"Health.recreational_drug",
		"Health.surgery",
		"Health.symptom",
		"Health.tests",
		"Health.treatment",
		"Health.trial",
		"Health.virus",
		"Health.vitamin",
		"Location.academy",
		"Location.airport",
		"Location.borough",
		"Location.bridge",
		"Location.building",
		"Location.canyon",
		"Location.city",
		"Location.city_area",
		"Location.continent",
		"Location.convention_centre",
		"Location.country",
		"Location.county",
		"Location.desert",
		"Location.direction",
		"Location.forest",
		"Location.government_residence",
		"Location.high_school",
		"Location.highway",
		"Location.hotel",
		"Location.island",
		"Location.lake",
		"Location.market",
		"Location.military_base",
		"Location.mountain",
		"Location.mountain_range",
		"Location.museum_or_gallery",
		"Location.neighborhood",
		"Location.nightclub",
		"Location.ocean",
		"Location.park",
		"Location.power_station",
		"Location.prison",
		"Location.public_space",
		"Location.region",
		"Location.religious_site",
		"Location.river",
		"Location.sea",
		"Location.stadium",
		"Location.state_or_province",
		"Location.statue",
		"Location.street",
		"Location.train_station",
		"Location.transit_line",
		"Location.university",
		"Location.ward",
		"Location.waterfall",
		"Number.distribution",
		"Number.economics",
		"Number.financials",
		"Number.math_constant",
		"Number.number",
		"Number.pricing",
		"Number.system",
		"Number.taxes",
		"Org.broadcaster",
		"Org.business",
		"Org.central_bank",
		"Org.college_sports_team",
		"Org.court",
		"Org.empire",
		"Org.fraternity_sorority",
		"Org.government",
		"Org.government_agency",
		"Org.government_committee",
		"Org.government_legislature",
		"Org.government_program",
		"Org.hackers",
		"Org.hospital",
		"Org.ideology",
		"Org.institute",
		"Org.intelligence_agency",
		"Org.junior_hockey_team",
		"Org.labor_union",
		"Org.law_enforcement",
		"Org.medical",
		"Org.militants",
		"Org.military",
		"Org.minor_league_baseball_team",
		"Org.music_group",
		"Org.news_agency",
		"Org.newspaper",
		"Org.nonprofit",
		"Org.online_news",
		"Org.political_movement",
		"Org.political_party",
		"Org.pro_baseball_team",
		"Org.pro_basketball_team",
		"Org.pro_football_team",
		"Org.pro_hockey_team",
		"Org.pro_rugby_team",
		"Org.pro_soccer_team",
		"Org.radio_station",
		"Org.religion",
		"Org.sports_league",
		"Org.standards",
		"Org.stock_exchange",
		"Org.stock_index",
		"Org.think_tank",
		"Org.trade_agreement",
		"Org.transit_authority",
		"Org.transit_system",
		"Org.treaty",
		"Person.academic",
		"Person.activist",
		"Person.actor",
		"Person.appearance",
		"Person.artist",
		"Person.astronaut",
		"Person.author",
		"Person.broadcaster",
		"Person.businessman",
		"Person.comedian",
		"Person.computer_scientist",
		"Person.criminal",
		"Person.director",
		"Person.economist",
		"Person.emotion",
		"Person.ethnicity",
		"Person.fictional_character",
		"Person.first_lady",
		"Person.first_nations",
		"Person.gender",
		"Person.government_employee",
		"Person.hacker",
		"Person.head_of_state_title",
		"Person.job_title",
		"Person.journalist",
		"Person.judge",
		"Person.language",
		"Person.law_enforcement",
		"Person.lawyer",
		"Person.military_personnel",
		"Person.military_rank",
		"Person.model",
		"Person.music_group",
		"Person.musician",
		"Person.nationality",
		"Person.philanthropist",
		"Person.philosopher",
		"Person.physician",
		"Person.playwright",
		"Person.poet",
		"Person.politician",
		"Person.pro_athlete",
		"Person.radio_host",
		"Person.relationship",
		"Person.religious_figure",
		"Person.religious_follower",
		"Person.religious_founder",
		"Person.royalty",
		"Person.scientist",
		"Person.software_engineer",
		"Person.sports_coach",
		"Person.sports_position",
		"Person.streamer",
		"Person.subculture",
		"Person.surgeon",
		"Person.terrorist",
		"Person.tv_presenter",
		"Person.us_president",
		"Person.whistleblower",
		"Person.world_leader",
		"Product.aircraft",
		"Product.album",
		"Product.automobile",
		"Product.beer",
		"Product.book",
		"Product.cargo_ship",
		"Product.cleaning",
		"Product.clothing",
		"Product.cocktail",
		"Product.coffee",
		"Product.commodity",
		"Product.cpu",
		"Product.cryptocurrency",
		"Product.currency",
		"Product.digital_media_player",
		"Product.ETF",
		"Product.fashion_accessory",
		"Product.financial",
		"Product.food",
		"Product.headphones",
		"Product.jewellery",
		"Product.laptop",
		"Product.laundry_detergent",
		"Product.magazine",
		"Product.manufacturing",
		"Product.military_ship",
		"Product.movie",
		"Product.musical_instrument",
		"Product.music_genre",
		"Product.personal_hygiene",
		"Product.pipeline_system",
		"Product.podcast",
		"Product.pornography",
		"Product.registered_investment",
		"Product.sex_toy",
		"Product.smartphone",
		"Product.smartwatch",
		"Product.soft_drink",
		"Product.space_shuttle",
		"Product.sports_equipment",
		"Product.tablet",
		"Product.tea",
		"Product.tv_episode",
		"Product.tv_show",
		"Product.vehicle",
		"Product.video_game",
		"Product.video_game_console",
		"Product.watch",
		"Product.weapon",
		"Product.wine",
		"Science.bacteria",
		"Science.chemical_compound",
		"Science.chemical_element",
		"Science.fatty_acids",
		"Science.galaxy",
		"Science.isotope",
		"Science.mineral",
		"Science.molecule",
		"Science.particle",
		"Science.planet",
		"Science.plant",
		"Science.protein",
		"Science.star",
		"Science.theory",
		"Technology.algorithm",
		"Technology.component",
		"Technology.cpu_architecture",
		"Technology.cpu_extensions",
		"Technology.datastructure",
		"Technology.encryption",
		"Technology.file_format",
		"Technology.imaging",
		"Technology.infotainment",
		"Technology.input_device",
		"Technology.markup",
		"Technology.mobile_interface",
		"Technology.network",
		"Technology.operating_system",
		"Technology.programming_language",
		"Technology.protocol",
		"Technology.security_exploit",
		"Technology.social_network",
		"Technology.software",
		"Technology.software_development_process",
		"Technology.software_license",
		"Technology.streaming_service",
		"Technology.typeface",
		"Technology.virtual_reality",
		"Time.day",
		"Time.holiday",
		"Time.month",
		"Time.period",
		"Time.season",
		"Time.time_of_day",
		"Time.year",
	}

	classesLookup = map[string]bool{
		"Animal.amphibian":                        true,
		"Animal.bird":                             true,
		"Animal.dog":                              true,
		"Animal.fish":                             true,
		"Animal.insect":                           true,
		"Animal.mammal":                           true,
		"Animal.racehorse":                        true,
		"Animal.reptile":                          true,
		"Event.activity":                          true,
		"Event.airplane_crash":                    true,
		"Event.award":                             true,
		"Event.coup":                              true,
		"Event.crime":                             true,
		"Event.festival":                          true,
		"Event.financial":                         true,
		"Event.genocide":                          true,
		"Event.legal":                             true,
		"Event.legislation":                       true,
		"Event.massacre":                          true,
		"Event.military_operation":                true,
		"Event.motor_race":                        true,
		"Event.pandemic":                          true,
		"Event.political":                         true,
		"Event.religion":                          true,
		"Event.social":                            true,
		"Event.space_mission":                     true,
		"Event.sport":                             true,
		"Event.sporting_event":                    true,
		"Event.sports_action":                     true,
		"Event.terrorist_attack":                  true,
		"Event.time_management":                   true,
		"Event.trade_show":                        true,
		"Event.trial":                             true,
		"Event.us_constitution":                   true,
		"Event.war":                               true,
		"Event.weather":                           true,
		"Health.alternative_medicine":             true,
		"Health.antibody":                         true,
		"Health.antigen":                          true,
		"Health.artery":                           true,
		"Health.body_part":                        true,
		"Health.bone":                             true,
		"Health.cancer":                           true,
		"Health.cell":                             true,
		"Health.condition":                        true,
		"Health.diet":                             true,
		"Health.disorder":                         true,
		"Health.enzyme":                           true,
		"Health.gene":                             true,
		"Health.hormone":                          true,
		"Health.muscle":                           true,
		"Health.organ":                            true,
		"Health.peptide":                          true,
		"Health.pharmaceutical":                   true,
		"Health.rate":                             true,
		"Health.recreational_drug":                true,
		"Health.surgery":                          true,
		"Health.symptom":                          true,
		"Health.tests":                            true,
		"Health.treatment":                        true,
		"Health.trial":                            true,
		"Health.virus":                            true,
		"Health.vitamin":                          true,
		"Location.academy":                        true,
		"Location.airport":                        true,
		"Location.borough":                        true,
		"Location.bridge":                         true,
		"Location.building":                       true,
		"Location.canyon":                         true,
		"Location.city":                           true,
		"Location.city_area":                      true,
		"Location.continent":                      true,
		"Location.convention_centre":              true,
		"Location.country":                        true,
		"Location.county":                         true,
		"Location.desert":                         true,
		"Location.direction":                      true,
		"Location.forest":                         true,
		"Location.government_residence":           true,
		"Location.high_school":                    true,
		"Location.highway":                        true,
		"Location.hotel":                          true,
		"Location.island":                         true,
		"Location.lake":                           true,
		"Location.market":                         true,
		"Location.military_base":                  true,
		"Location.mountain":                       true,
		"Location.mountain_range":                 true,
		"Location.museum_or_gallery":              true,
		"Location.neighborhood":                   true,
		"Location.nightclub":                      true,
		"Location.ocean":                          true,
		"Location.park":                           true,
		"Location.power_station":                  true,
		"Location.prison":                         true,
		"Location.public_space":                   true,
		"Location.region":                         true,
		"Location.religious_site":                 true,
		"Location.river":                          true,
		"Location.sea":                            true,
		"Location.stadium":                        true,
		"Location.state_or_province":              true,
		"Location.statue":                         true,
		"Location.street":                         true,
		"Location.train_station":                  true,
		"Location.transit_line":                   true,
		"Location.university":                     true,
		"Location.ward":                           true,
		"Location.waterfall":                      true,
		"Number.distribution":                     true,
		"Number.economics":                        true,
		"Number.financials":                       true,
		"Number.math_constant":                    true,
		"Number.number":                           true,
		"Number.pricing":                          true,
		"Number.system":                           true,
		"Number.taxes":                            true,
		"Org.broadcaster":                         true,
		"Org.business":                            true,
		"Org.central_bank":                        true,
		"Org.college_sports_team":                 true,
		"Org.court":                               true,
		"Org.empire":                              true,
		"Org.fraternity_sorority":                 true,
		"Org.government":                          true,
		"Org.government_agency":                   true,
		"Org.government_committee":                true,
		"Org.government_legislature":              true,
		"Org.government_program":                  true,
		"Org.hackers":                             true,
		"Org.hospital":                            true,
		"Org.ideology":                            true,
		"Org.institute":                           true,
		"Org.intelligence_agency":                 true,
		"Org.junior_hockey_team":                  true,
		"Org.labor_union":                         true,
		"Org.law_enforcement":                     true,
		"Org.medical":                             true,
		"Org.militants":                           true,
		"Org.military":                            true,
		"Org.minor_league_baseball_team":          true,
		"Org.music_group":                         true,
		"Org.news_agency":                         true,
		"Org.newspaper":                           true,
		"Org.nonprofit":                           true,
		"Org.online_news":                         true,
		"Org.political_movement":                  true,
		"Org.political_party":                     true,
		"Org.pro_baseball_team":                   true,
		"Org.pro_basketball_team":                 true,
		"Org.pro_football_team":                   true,
		"Org.pro_hockey_team":                     true,
		"Org.pro_rugby_team":                      true,
		"Org.pro_soccer_team":                     true,
		"Org.radio_station":                       true,
		"Org.religion":                            true,
		"Org.sports_league":                       true,
		"Org.standards":                           true,
		"Org.stock_exchange":                      true,
		"Org.stock_index":                         true,
		"Org.think_tank":                          true,
		"Org.trade_agreement":                     true,
		"Org.transit_authority":                   true,
		"Org.transit_system":                      true,
		"Org.treaty":                              true,
		"Person.academic":                         true,
		"Person.activist":                         true,
		"Person.actor":                            true,
		"Person.appearance":                       true,
		"Person.artist":                           true,
		"Person.astronaut":                        true,
		"Person.author":                           true,
		"Person.broadcaster":                      true,
		"Person.businessman":                      true,
		"Person.comedian":                         true,
		"Person.computer_scientist":               true,
		"Person.criminal":                         true,
		"Person.director":                         true,
		"Person.economist":                        true,
		"Person.emotion":                          true,
		"Person.ethnicity":                        true,
		"Person.fictional_character":              true,
		"Person.first_lady":                       true,
		"Person.first_nations":                    true,
		"Person.gender":                           true,
		"Person.government_employee":              true,
		"Person.hacker":                           true,
		"Person.head_of_state_title":              true,
		"Person.job_title":                        true,
		"Person.journalist":                       true,
		"Person.judge":                            true,
		"Person.language":                         true,
		"Person.law_enforcement":                  true,
		"Person.lawyer":                           true,
		"Person.military_personnel":               true,
		"Person.military_rank":                    true,
		"Person.model":                            true,
		"Person.music_group":                      true,
		"Person.musician":                         true,
		"Person.nationality":                      true,
		"Person.philanthropist":                   true,
		"Person.philosopher":                      true,
		"Person.physician":                        true,
		"Person.playwright":                       true,
		"Person.poet":                             true,
		"Person.politician":                       true,
		"Person.pro_athlete":                      true,
		"Person.radio_host":                       true,
		"Person.relationship":                     true,
		"Person.religious_figure":                 true,
		"Person.religious_follower":               true,
		"Person.religious_founder":                true,
		"Person.royalty":                          true,
		"Person.scientist":                        true,
		"Person.software_engineer":                true,
		"Person.sports_coach":                     true,
		"Person.sports_position":                  true,
		"Person.streamer":                         true,
		"Person.subculture":                       true,
		"Person.surgeon":                          true,
		"Person.terrorist":                        true,
		"Person.tv_presenter":                     true,
		"Person.us_president":                     true,
		"Person.whistleblower":                    true,
		"Person.world_leader":                     true,
		"Product.aircraft":                        true,
		"Product.album":                           true,
		"Product.automobile":                      true,
		"Product.beer":                            true,
		"Product.book":                            true,
		"Product.cargo_ship":                      true,
		"Product.cleaning":                        true,
		"Product.clothing":                        true,
		"Product.cocktail":                        true,
		"Product.coffee":                          true,
		"Product.commodity":                       true,
		"Product.cpu":                             true,
		"Product.cryptocurrency":                  true,
		"Product.currency":                        true,
		"Product.digital_media_player":            true,
		"Product.ETF":                             true,
		"Product.fashion_accessory":               true,
		"Product.financial":                       true,
		"Product.food":                            true,
		"Product.headphones":                      true,
		"Product.jewellery":                       true,
		"Product.laptop":                          true,
		"Product.laundry_detergent":               true,
		"Product.magazine":                        true,
		"Product.manufacturing":                   true,
		"Product.military_ship":                   true,
		"Product.movie":                           true,
		"Product.musical_instrument":              true,
		"Product.music_genre":                     true,
		"Product.personal_hygiene":                true,
		"Product.pipeline_system":                 true,
		"Product.podcast":                         true,
		"Product.pornography":                     true,
		"Product.registered_investment":           true,
		"Product.sex_toy":                         true,
		"Product.smartphone":                      true,
		"Product.smartwatch":                      true,
		"Product.soft_drink":                      true,
		"Product.space_shuttle":                   true,
		"Product.sports_equipment":                true,
		"Product.tablet":                          true,
		"Product.tea":                             true,
		"Product.tv_episode":                      true,
		"Product.tv_show":                         true,
		"Product.vehicle":                         true,
		"Product.video_game":                      true,
		"Product.video_game_console":              true,
		"Product.watch":                           true,
		"Product.weapon":                          true,
		"Product.wine":                            true,
		"Science.bacteria":                        true,
		"Science.chemical_compound":               true,
		"Science.chemical_element":                true,
		"Science.fatty_acids":                     true,
		"Science.galaxy":                          true,
		"Science.isotope":                         true,
		"Science.mineral":                         true,
		"Science.molecule":                        true,
		"Science.particle":                        true,
		"Science.planet":                          true,
		"Science.plant":                           true,
		"Science.protein":                         true,
		"Science.star":                            true,
		"Science.theory":                          true,
		"Technology.algorithm":                    true,
		"Technology.component":                    true,
		"Technology.cpu_architecture":             true,
		"Technology.cpu_extensions":               true,
		"Technology.datastructure":                true,
		"Technology.encryption":                   true,
		"Technology.file_format":                  true,
		"Technology.imaging":                      true,
		"Technology.infotainment":                 true,
		"Technology.input_device":                 true,
		"Technology.markup":                       true,
		"Technology.mobile_interface":             true,
		"Technology.network":                      true,
		"Technology.operating_system":             true,
		"Technology.programming_language":         true,
		"Technology.protocol":                     true,
		"Technology.security_exploit":             true,
		"Technology.social_network":               true,
		"Technology.software":                     true,
		"Technology.software_development_process": true,
		"Technology.software_license":             true,
		"Technology.streaming_service":            true,
		"Technology.typeface":                     true,
		"Technology.virtual_reality":              true,
		"Time.day":                                true,
		"Time.holiday":                            true,
		"Time.month":                              true,
		"Time.period":                             true,
		"Time.season":                             true,
		"Time.time_of_day":                        true,
		"Time.year":                               true,
	}
)

type classification string

func (c classification) QueryString() string {
	return string(c) + ":*"
}

func HasClass(args ...string) bool {
	for _, arg := range args {
		if _, ok := classesLookup[arg]; ok {
			return true
		}
	}

	return false
}
